- name: php repository for 5.6
  apt_repository: repo="ppa:ondrej/php"

- name: PHP 5.6 packages
  apt:
    name:
      - php5.6-fpm
      - php5.6-bz2
      - php5.6-cli
      - php5.6-curl
      - php5.6-gd
      - php5.6-imap
      - php5.6-json
      - php5.6-mbstring
      - php5.6-mysql
      - php5.6-opcache
      - php5.6-readline
      - php5.6-xmlrpc
      - php5.6-xsl
      - php5.6-zip
      - php-gettext
  notify:
     - reload php5.6

- name: Enable PHP 5.6
  file: src=../conf-available/php5.6-fpm.conf dest=/etc/apache2/conf-enabled/php5.6-fpm.conf state=link force=yes
  notify:
      - reload apache

