- name: PHP 7.2 packages
  apt:
    name:
      - php7.2-fpm
      - php7.2-bz2
      - php7.2-cli
      - php7.2-curl
      - php7.2-gd
      - php7.2-imap
      - php7.2-json
      - php7.2-mbstring
      - php7.2-mysql
      - php7.2-opcache
      - php7.2-readline
      - php7.2-xmlrpc
      - php7.2-xsl
      - php7.2-zip
      - php-gettext
  notify:
     - reload php7.2

- name: Enable PHP 7.2
  file: src=../conf-available/php7.2-fpm.conf dest=/etc/apache2/conf-enabled/php7.2-fpm.conf state=link force=yes
  notify:
      - reload apache

